-- Insert Lawyers Beginner Assessment
INSERT INTO public.assessment_products (
  slug,
  name,
  track,
  role,
  difficulty_level,
  duration_minutes,
  question_count,
  total_points,
  passing_score,
  presentation_mode,
  adaptive_selection,
  irt_enabled,
  dimension_codes,
  json_file_path,
  target_audience,
  description,
  is_active,
  display_order
) VALUES (
  'lawyer-beginner',
  'Lawyers - Beginner',
  'role-based',
  'Lawyers',
  'beginner',
  60,
  60,
  600,
  420,
  'fixed-sequential',
  false,
  false,
  '["LAI", "PEL", "CER", "IAV", "LLC", "EGC", "CSL", "TLS"]'::jsonb,
  'lawyer-beginner.json',
  'Lawyers, paralegals, legal researchers, corporate counsel, litigation attorneys',
  'Foundational AI literacy assessment for legal practice',
  true,
  60
);

-- Insert Lawyers Advanced Assessment
INSERT INTO public.assessment_products (
  slug,
  name,
  track,
  role,
  difficulty_level,
  duration_minutes,
  question_count,
  total_bank_items,
  total_points,
  passing_score,
  presentation_mode,
  adaptive_selection,
  irt_enabled,
  dimension_codes,
  json_file_path,
  target_audience,
  description,
  is_active,
  display_order
) VALUES (
  'lawyer-advanced',
  'Lawyers - Advanced',
  'role-based',
  'Lawyers',
  'advanced',
  85,
  80,
  160,
  800,
  640,
  'adaptive-sequential',
  true,
  true,
  '["LAI", "PEL", "CER", "IAV", "LLC", "EGC", "CSL", "TLS"]'::jsonb,
  'lawyer-advanced.json',
  'Managing Partner, General Counsel, Practice Leader, Senior Litigator',
  'Expert-level AI literacy assessment for legal leadership',
  true,
  61
);

-- Insert Management Consultants Beginner Assessment
INSERT INTO public.assessment_products (
  slug,
  name,
  track,
  role,
  difficulty_level,
  duration_minutes,
  question_count,
  total_points,
  passing_score,
  presentation_mode,
  adaptive_selection,
  irt_enabled,
  dimension_codes,
  json_file_path,
  target_audience,
  description,
  is_active,
  display_order
) VALUES (
  'mc-beginner',
  'Management Consultants - Beginner',
  'role-based',
  'Management Consultants',
  'beginner',
  60,
  60,
  600,
  420,
  'fixed-sequential',
  false,
  false,
  '["CAI", "STA", "CDA", "PIA", "CMA", "DDA", "EIS", "CIT"]'::jsonb,
  'mc-beginner.json',
  'Management consultants, strategy consultants, business advisors',
  'Foundational AI literacy assessment for consulting practice',
  true,
  62
);

-- Insert Management Consultants Advanced Assessment
INSERT INTO public.assessment_products (
  slug,
  name,
  track,
  role,
  difficulty_level,
  duration_minutes,
  question_count,
  total_bank_items,
  total_points,
  passing_score,
  presentation_mode,
  adaptive_selection,
  irt_enabled,
  dimension_codes,
  json_file_path,
  target_audience,
  description,
  is_active,
  display_order
) VALUES (
  'mc-advanced',
  'Management Consultants - Advanced',
  'role-based',
  'Management Consultants',
  'advanced',
  85,
  80,
  160,
  800,
  640,
  'adaptive-sequential',
  true,
  true,
  '["CAI", "STA", "CDA", "PIA", "CMA", "DDA", "EIS", "CIT"]'::jsonb,
  'mc-advanced.json',
  'Senior Management Consultant, Strategy Partner, Practice Leader',
  'Expert-level AI literacy assessment for consulting leadership',
  true,
  63
);