-- Insert Doctors Beginner assessment product
INSERT INTO public.assessment_products (
  slug,
  name,
  track,
  role,
  difficulty_level,
  duration_minutes,
  question_count,
  total_points,
  passing_score,
  presentation_mode,
  adaptive_selection,
  irt_enabled,
  dimension_codes,
  json_file_path,
  target_audience,
  description,
  is_active,
  display_order
) VALUES (
  'doc-beginner',
  'Doctors - Beginner',
  'role-based',
  'Doctors',
  'beginner',
  60,
  60,
  600,
  420,
  'fixed-sequential',
  false,
  false,
  '["MDA", "CDM", "PDM", "DSA", "CRD", "EGC", "RAC", "TAS"]'::jsonb,
  'doc-beginner.json',
  'Physicians, medical residents, clinical practitioners',
  'Foundational AI literacy for clinical practice',
  true,
  700
);

-- Insert Doctors Advanced assessment product
INSERT INTO public.assessment_products (
  slug,
  name,
  track,
  role,
  difficulty_level,
  duration_minutes,
  question_count,
  total_bank_items,
  total_points,
  passing_score,
  presentation_mode,
  adaptive_selection,
  irt_enabled,
  dimension_codes,
  json_file_path,
  target_audience,
  description,
  is_active,
  display_order
) VALUES (
  'doc-advanced',
  'Doctors - Advanced',
  'role-based',
  'Doctors',
  'advanced',
  85,
  80,
  160,
  800,
  640,
  'adaptive-sequential',
  true,
  true,
  '["MDA", "CDM", "PDM", "DSA", "CRD", "EGC", "RAC", "TAS"]'::jsonb,
  'doc-advanced.json',
  'Chief Medical Officer, Medical Director, Senior Physician Leader',
  'Expert-level AI literacy for clinical leadership',
  true,
  701
);

-- Insert Financial Advisors Beginner assessment product
INSERT INTO public.assessment_products (
  slug,
  name,
  track,
  role,
  difficulty_level,
  duration_minutes,
  question_count,
  total_points,
  passing_score,
  presentation_mode,
  adaptive_selection,
  irt_enabled,
  dimension_codes,
  json_file_path,
  target_audience,
  description,
  is_active,
  display_order
) VALUES (
  'fa-beginner',
  'Financial Advisors - Beginner',
  'role-based',
  'Financial Advisors',
  'beginner',
  60,
  60,
  600,
  420,
  'fixed-sequential',
  false,
  false,
  '["FAI", "CPA", "RIA", "PFA", "CRE", "EGC", "RAC", "TAP"]'::jsonb,
  'fa-beginner.json',
  'Financial advisors, wealth managers, investment advisors',
  'Foundational AI literacy for financial advisory',
  true,
  800
);

-- Insert Financial Advisors Advanced assessment product
INSERT INTO public.assessment_products (
  slug,
  name,
  track,
  role,
  difficulty_level,
  duration_minutes,
  question_count,
  total_bank_items,
  total_points,
  passing_score,
  presentation_mode,
  adaptive_selection,
  irt_enabled,
  dimension_codes,
  json_file_path,
  target_audience,
  description,
  is_active,
  display_order
) VALUES (
  'fa-advanced',
  'Financial Advisors - Advanced',
  'role-based',
  'Financial Advisors',
  'advanced',
  85,
  80,
  160,
  800,
  640,
  'adaptive-sequential',
  true,
  true,
  '["FAI", "CPA", "RIA", "PFA", "CRE", "EGC", "RAC", "TAP"]'::jsonb,
  'fa-advanced.json',
  'Senior Financial Advisor, Wealth Management Leader, CIO',
  'Expert-level AI literacy for financial advisory leadership',
  true,
  801
);