-- Add Teachers Professional Assessments to assessment_products table

-- Teachers Beginner Assessment (60 fixed items, 600 points, 70% pass)
INSERT INTO public.assessment_products (
  name,
  slug,
  track,
  role,
  difficulty_level,
  description,
  target_audience,
  json_file_path,
  duration_minutes,
  question_count,
  dimension_codes,
  total_points,
  passing_score,
  is_active,
  display_order,
  total_bank_items,
  adaptive_selection,
  irt_enabled,
  presentation_mode
) VALUES (
  'Teachers - Beginner',
  'teachers-beginner',
  'role-based',
  'Teachers',
  'beginner',
  'Foundational assessment for K-12 teachers and educators on AI-enhanced teaching and learning',
  'K-12 teachers, instructional coaches, and educators seeking to integrate AI into their practice',
  'teachers-beginner.json',
  60,
  60,
  '["TEA", "PLD", "ASE", "CAI", "EAI", "EGC", "ACI", "TAS"]'::jsonb,
  600,
  420,
  true,
  31,
  60,
  false,
  false,
  'fixed-sequential'
);

-- Teachers Advanced Assessment (80 IRT items from 160 bank, 800 points, 80% pass)
INSERT INTO public.assessment_products (
  name,
  slug,
  track,
  role,
  difficulty_level,
  description,
  target_audience,
  json_file_path,
  duration_minutes,
  question_count,
  dimension_codes,
  total_points,
  passing_score,
  is_active,
  display_order,
  total_bank_items,
  adaptive_selection,
  irt_enabled,
  presentation_mode
) VALUES (
  'Teachers - Advanced',
  'teachers-advanced',
  'role-based',
  'Teachers',
  'advanced',
  'Advanced IRT-based assessment for experienced teachers and educational leaders',
  'Master teachers, instructional leaders, curriculum directors, and school administrators',
  'teachers-advanced.json',
  80,
  80,
  '["TEA", "PLD", "ASE", "CAI", "EAI", "EGC", "ACI", "TAS"]'::jsonb,
  800,
  640,
  true,
  32,
  160,
  true,
  true,
  'adaptive-sequential'
);