-- Insert Healthcare Administrators Beginner assessment
INSERT INTO public.assessment_products (
  slug,
  name,
  track,
  role,
  difficulty_level,
  duration_minutes,
  question_count,
  total_points,
  passing_score,
  presentation_mode,
  adaptive_selection,
  irt_enabled,
  dimension_codes,
  json_file_path,
  target_audience,
  description,
  is_active,
  display_order
) VALUES (
  'ha-beginner',
  'Healthcare Administrators - Beginner',
  'role-based',
  'Healthcare Administrators',
  'beginner',
  60,
  60,
  600,
  420,
  'fixed-sequential',
  false,
  false,
  '["HAI", "OPM", "FRM", "QPS", "WFM", "EGC", "SIM", "TAS"]'::jsonb,
  'ha-beginner.json',
  'Healthcare administrators, hospital executives, health system managers',
  'Foundational AI literacy for healthcare administration',
  true,
  140
);

-- Insert Healthcare Administrators Advanced assessment
INSERT INTO public.assessment_products (
  slug,
  name,
  track,
  role,
  difficulty_level,
  duration_minutes,
  question_count,
  total_bank_items,
  total_points,
  passing_score,
  presentation_mode,
  adaptive_selection,
  irt_enabled,
  dimension_codes,
  json_file_path,
  target_audience,
  description,
  is_active,
  display_order
) VALUES (
  'ha-advanced',
  'Healthcare Administrators - Advanced',
  'role-based',
  'Healthcare Administrators',
  'advanced',
  85,
  80,
  160,
  800,
  640,
  'adaptive-sequential',
  true,
  true,
  '["HAI", "OPM", "FRM", "QPS", "WFM", "EGC", "SIM", "TAS"]'::jsonb,
  'ha-advanced.json',
  'Hospital CEO, Chief Medical Officer, VP Clinical Operations',
  'Expert-level AI literacy for healthcare leadership',
  true,
  141
);